[package]
name = "holyc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "HolyC compiler CLI"
default-run = "holycc"

[[bin]]
name = "holycc"
path = "src/main.rs"

[lib]
name = "holyc"
path = "src/lib.rs"

[dependencies]
holyc-syntax = { path = "../holyc-syntax" }
holyc-ast = { path = "../holyc-ast" }
holyc-parse = { path = "../holyc-parse" }
holyc-sema = { path = "../holyc-sema" }
holyc-codegen = { path = "../holyc-codegen" }
templeos-compat = { path = "../templeos-compat" }
thiserror.workspace = true
